-- Tabela de Países
CREATE TABLE IF NOT EXISTS L001 (
    L001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    L001_Name VARCHAR(100),
    L001_Abbreviation CHAR(2),
    L001_Is_Active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT = 'Countries';

-- Tabela de Estados
CREATE TABLE IF NOT EXISTS L002 (
    L002_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    L002_L001_Id INT(15) UNSIGNED,
    L002_Name VARCHAR(100),
    L002_UF CHAR(2),
    L002_Is_Active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (L002_L001_Id) REFERENCES L001(L001_Id)
) COMMENT = 'States';

-- Tabela de Cidades
CREATE TABLE IF NOT EXISTS L003 (
    L003_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    L003_L002_Id INT(15) UNSIGNED,
    L003_Name VARCHAR(100),
    L003_Is_Active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (L003_L002_Id) REFERENCES L002(L002_Id)
) COMMENT = 'Cities';

-- Tabela de Endereços
CREATE TABLE IF NOT EXISTS L004 (
    L004_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    L004_Street VARCHAR(100),
    L004_Number VARCHAR(20),
    L004_Complement VARCHAR(60),
    L004_District VARCHAR(60),
    L004_ZipCode VARCHAR(10),
    L004_L003_Id INT(15) UNSIGNED,
    L004_Is_Active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (L004_L003_Id) REFERENCES L003(L003_Id)
) COMMENT = 'Addresses';

-- Tabela de Empresas
CREATE TABLE IF NOT EXISTS C001 (
    C001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    C001_L004_Id INT(15) UNSIGNED,
    C001_Company_Name VARCHAR(60),
    C001_Trade_Name VARCHAR(60),
    C001_Short_Name VARCHAR(60),
    C001_State_Registration VARCHAR(14),
    C001_Secondary_State_Registration VARCHAR(20),
    C001_Municipal_Registration VARCHAR(15),
    C001_CNAE VARCHAR(7),
    C001_Tax_Regime_Code INT,
    C001_CNPJ VARCHAR(18),
    C001_Phone VARCHAR(14),
    C001_Whatsapp VARCHAR(14),
    C001_Website VARCHAR(100),
    C001_Logo VARCHAR(20),
    C001_Is_Active ENUM('S','N') DEFAULT 'S',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (C001_L004_Id) REFERENCES L004(L004_Id)
) COMMENT = 'Registered stores';

-- Tabela de Categorias
CREATE TABLE IF NOT EXISTS C002 (
    C002_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    C002_Name VARCHAR(255),
    C002_Description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT = 'Categories';

-- Tabela de Marketplaces
CREATE TABLE IF NOT EXISTS M001 (
    M001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    M001_Name VARCHAR(100),
    M001_Api_Url VARCHAR(255),
    M001_Is_Active BOOLEAN,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT = 'Integrated marketplaces';

-- Tabela de Usuários
CREATE TABLE IF NOT EXISTS U001 (
    U001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    U001_Name VARCHAR(255),
    U001_CPF VARCHAR(20),
    U001_Email VARCHAR(100),
    U001_Password VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT = 'System users';

-- Tabela de Produtos
CREATE TABLE IF NOT EXISTS P001 (
    P001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    P001_C001_Id INT(15) UNSIGNED,
    P001_C002_Id INT(15) UNSIGNED,
    P001_EAN VARCHAR(20),
    P001_Name VARCHAR(255),
    P001_Title VARCHAR(100),
    P001_Description TEXT,
    P001_Cost_Price DECIMAL(10,2),
    P001_Price DECIMAL(10,2),
    P001_Brand VARCHAR(100),
    P001_Weight DECIMAL(10,2),
    P001_Height DECIMAL(10,2),
    P001_Width DECIMAL(10,2),
    P001_Length DECIMAL(10,2),
    P001_Is_Active BOOLEAN,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (P001_C001_Id) REFERENCES C001(C001_Id),
    FOREIGN KEY (P001_C002_Id) REFERENCES C002(C002_Id)
) COMMENT = 'Registered products';

-- Tabela de Anúncios
CREATE TABLE IF NOT EXISTS P002 (
    P002_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    P002_M001_Id INT(15) UNSIGNED,
    P002_P001_Id INT(15) UNSIGNED,
    P002_Internal_Code VARCHAR(100),
    P002_Title VARCHAR(100),
    P002_Price DECIMAL(10,2),
    P002_Stock INT,
    P002_Status VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (P002_M001_Id) REFERENCES M001(M001_Id),
    FOREIGN KEY (P002_P001_Id) REFERENCES P001(P001_Id)
) COMMENT = 'Ads';

-- Tabela de Imagens de Produtos
CREATE TABLE IF NOT EXISTS I001 (
    I001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    I001_P001_Id INT(15) UNSIGNED,
    I001_File TEXT NOT NULL,
    I001_Order INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (I001_P001_Id) REFERENCES P001(P001_Id)
) COMMENT = 'Product images';

-- Tabela de Atributos de Variações
CREATE TABLE IF NOT EXISTS H001 (
    H001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    H001_P002_Id INT(15) UNSIGNED,
    H001_Type VARCHAR(100),
    H001_Value VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (H001_P002_Id) REFERENCES P002(P002_Id)
) COMMENT = 'Variation attributes';

-- Tabela de Credenciais de API
CREATE TABLE IF NOT EXISTS S001 (
    S001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    S001_U001_Id INT(15) UNSIGNED,
    S001_C001_Id INT(15) UNSIGNED,
    S001_Api_Key VARCHAR(255),
    S001_Api_Secret VARCHAR(255),
    S001_Access_Token VARCHAR(255),
    S001_Token_Expiry DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (S001_U001_Id) REFERENCES U001(U001_Id),
    FOREIGN KEY (S001_C001_Id) REFERENCES C001(C001_Id)
) COMMENT = 'API Credentials';

-- Tabela de Fila de Atualizações
CREATE TABLE IF NOT EXISTS Q001 (
    Q001_Id INT(15) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Q001_P002_Id INT(15) UNSIGNED,
    Q001_S001_Id INT(15) UNSIGNED,
    Q001_Update_Type VARCHAR(100),
    Q001_Status VARCHAR(50),
    Q001_Attempts INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Q001_P002_Id) REFERENCES P002(P002_Id),
    FOREIGN KEY (Q001_S001_Id) REFERENCES S001(S001_Id)
) COMMENT = 'Update queue';

-- Tabela de Logs de Atualizações
CREATE TABLE IF NOT EXISTS Q002 (
    Q002_Id INT(15) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Q002_P002_Id INT(15) UNSIGNED,
    Q002_Message TEXT,
    Q002_Previous_Status VARCHAR(50),
    Q002_New_Status VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Q002_P002_Id) REFERENCES P002(P002_Id)
) COMMENT = 'Update logs';


